### ISSUE TITLE
If body already has padding-bottom set, it's overwritten

### ISSUE THREAD

**Issue by richbradshaw** [maximebf/php-debugbar#149]
In my app the footer is fixed and positioned at the bottom. The body had padding-bottom set as 133px. The debug bar overwrites that and sets it at 26px which interferes with my styling.

Can I suggest that the debug bar reads the padding first, and if it's not set or < 26 sets it, else ignores it?

**Comment by mnpenner** [comment]
2nded. This looks bad with my sticky footer.

**Comment by barryvdh** [comment]
Hmm, hoping to do this without a toggle option in PHP /cc @xapon
Any ideas?

**Comment by richbradshaw** [comment]
Sorry - only just saw your email back from October :(

Can this not be read using JS - isn't it purely a rendering issue rather than a config/set up issue?

**Comment by barryvdh** [comment]
That is what I hope, yes. If someone could create an simple view that I can just render to see the problem, it would help.

An actual CSS (or js) solution that 'just works' would be great

**Comment by richbradshaw** [comment]
I'll look - our issue is that we don't have the debug bar on live, only on dev, so there isn't an easy way for me to just give you a URL, we'd need to build and push a new version somewhere. (I'll try and get that done at some point!)

In terms of what actually happens, <body> gets an inline style with `padding-bottom: 26px;` added to it, which has higher specificity than the stylesheet - if whatever adds that was able to detect if <body> already had padding and did nothing it it did, that would fix for me at least!

To make this happen, just have a CSS rule like

    body {
        padding-bottom:1000px;
    }

and includ the debug bar - it will overwrite it.

**Comment by barryvdh** [comment]
But sticky footers could like different, right? So need to be sure what to handle.

Eg, example from Bootstrap: https://gist.github.com/barryvdh/4ae10330922ace3497b3

**Comment by richbradshaw** [comment]
Yeah, I agree.

In that case it's using margin - maybe I should just switch to that.

I'd assume that what I'm saying is true though - if there is existing padding, either don't add the inline style, or, do, but add it on (e.g. if existing padding-bottom = 100, then make it 126)

To be honest, we've lived with this for over a year now, and as it's only a problem on dev, we don't mind much - it looks OK on live.

**Comment by barryvdh** [comment]
So something like #242 ?

**Comment by richbradshaw** [comment]
Yeah - that looks sensible to me - that would fix our problem as far as I can tell.

**Comment by codewizz** [comment]
Hello, is there any ETA for this fix to be applied to the debugbar codebase?

**Comment by barryvdh** [comment]
Does that fix work for you?

**Comment by barryvdh** [comment]
I've merged it, so please check with the latest dev.

**Comment by codewizz** [comment]
Thanks! It looks like to work better now but not perfectly. The only problem I see is when webpage has a footer set with an absolute position.

```css
footer {
    width: 100%;
    height: 40px;
    position: absolute;
    bottom: 0;
    left: 0;
}
```

In this case when debugbar is being expanded then footer shrinks and finally hides under the debugbar panel. It looks like this happens because of an inline padding-bottom style on a body element. I did some more testing and it looks like the way to solve this is to replace padding-bottom with a margin-bottom style. I am not aware of other side effects doing this but it looks like to work perfectly for the case described above.

Looking forward!

**Comment by barryvdh** [comment]
Can you create a test case + or?

**Comment by barryvdh** [comment]
*PR

**Comment by mnpenner** [comment]
Still doesn't look good in little-square-mode. Could you remove the `padding-bottom` altogether when the bar is collapsed to just the square? That way it will float over top of our footers, but since it's so small, it's not a big deal -- better than creating a big white gap below the footer.

**Comment by codewizz** [comment]
Here is a padding-bottom to margin-bottom replacement: #252

**Comment by mnpenner** [comment]
@codewizz If I can figure out how to install your fork instead of maximebf's, I'd be happy to try it out. I know it's a bit off-topic, but this won't install:

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/codewizz/php-debugbar"
    }
],
"require": {
    "codewizz/php-debugbar": "dev-master#a238151cabccffe091e9902978d37688d05d9b05",
```

**Comment by barryvdh** [comment]
Just download the normal one and replace the changed file manually.

**Comment by mnpenner** [comment]
Ahah! I forgot I had copied the resources out of vendor/ into my public dir so I could serve them up. Had to manually update them anyway :-) Both versions work fine actually. The DebugBar covers up my footer now, but that's fine for dev; I think it's never than adding a scrollbar to pages that didn't otherwise have them.

**Comment by codewizz** [comment]
@mnpenner I have adjusted my PR to remove margin-bottom inline style from the body element (this also removes a scrollbar from the pages that didn't had them) once debug bar is minimized or closed. Could you test and let me know if this works for you? :-)

**Comment by codewizz** [comment]
@barryvdh here are some working examples I just made as requested to see problem / solution in action. Both examples are identical except padding and margin.

http://debugbar.padding.codewizz.com/ - this one is using the old padding-bottom inline style (just try to expand the debugbar, you will see the footer starts to shrinking and finally hides under the debugbar panel)
http://debugbar.margin.codewizz.com/ - this one is using the new margin-bottom inline style (at first it looks like the footer is being overlapped but you can scroll down and see all the web content like it should be displayed, also I have added margin-bottom style removal from body once debugbar is closed or minimized).

I hope this helps!

**Comment by codewizz** [comment]
@barryvdh did you have time to check PR #252 and test cases? Would it be possible to merge these changes to a debugbar codebase? Thanks.

**Comment by mnpenner** [comment]
@codewizz Sorry, it took me some time to get back to this. I just tried with the latest Resources from your repo.

Now that I've played around with it a bit more, both these versions are bad actually. They don't cause a scrollbar to appear when the bar is minified, which is good, but when the bar is expanded, still no scrollbar appears which means the bar covers half my page and there's no way for me to uncover it without closing the bar because I can't scroll.

**Comment by codewizz** [comment]
@mnpenner do you have a working example that could show an actual problem you are having, so I could take a quick look at?

**Comment by mnpenner** [comment]
@codewizz Uhh....it's proprietary and massive. I've tried to put together [an example](https://trinket.io/html/69abb4b1b8) with our CSS, but I couldn't get the bar to show up and I don't want to spend too much time debugging it. If you can get the bar to display you might be able to see the problem.

**Comment by codewizz** [comment]
@mnpenner I copy pasted your [example](http://debugbar.margin.codewizz.com/mnpenner) to my development server. It looks like to work as it should for me. Could you please clarify or am I missing something?

**Comment by mnpenner** [comment]
@codewizz Hrm.. that does seem to be behaving correctly. I probably messed something up on my end. Maybe I have some conflicting JavaScript. Anyway, not to worry; it doesn't look like a problem with DebugBar. I'm happy with this if you guys want to push that PR through.

**Comment by codewizz** [comment]
@mnpenner thanks! I am still waiting for @barryvdh response if #252 PR could be merged to the DebugBar codebase.

**Comment by theTrip73** [comment]
One of my less active projects just got this PR during a composer update. On pages where a scroll bar already appears, I now get a second scroll bar.

I used Dev Tools to tweak the body element's style back and forth between padding-bottom and margin-bottom. When switching from the old padding-bottom to margin-bottom, the original scroll bar basically pops inside to make room for a second scrollbar that essentially buffers the main area by the height of the padding.

Is anyone else seeing this behavior, or do I have to go find some weird style definition buried in my designer's SCSS?

**Comment by codewizz** [comment]
@theTrip73 would it be possible to see a demo that reproduces the problem you are experiencing? I am using php-debugbar a lot in my projects and haven't experienced the problem you have described yet.

**Comment by theTrip73** [comment]
I verified that my other projects were already using updated debug bars and not experiencing this effect. Then I was able to track it down to an 'overflow-x: hidden;' property on "html, body", so it's on me to figure out why the original designer added that overflow-x. (Fun. /eyeroll)

Thanks for offering to look into it a bit.

**Comment by codewizz** [comment]
@theTrip73 you are welcome. Happy debugging! :-)
